<a href="https://colab.research.google.com/github/daniyal9538/GeneralProjects/blob/master/ai_article_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

import numpy as np
import tensorflow.keras as keras
import tensorflow as tf

In [0]:

#generate data
#(C + ~B) * ~A

data = [0]*8


data[0] = [[0, 0, 0] , [1]]
data[1] = [[0, 0, 1] , [1]]
data[2] = [[0, 1, 0] , [0]]
data[3] = [[0, 1, 1] , [1]]
data[4] = [[1, 0, 0] , [0]]
data[5] = [[1, 0, 1] , [0]]
data[6] = [[1, 1, 0] , [0]]
data[7] = [[1, 1, 1] , [0]]



for i in data:
  print(i)

[[0, 0, 0], [1]]
[[0, 0, 1], [1]]
[[0, 1, 0], [0]]
[[0, 1, 1], [1]]
[[1, 0, 0], [0]]
[[1, 0, 1], [0]]
[[1, 1, 0], [0]]
[[1, 1, 1], [0]]


In [0]:
size = 10000
dataSet = [0]*size
x_train =[]
y_train = []

for i in range(size):
   x_train.append(np.array(data[i%8][0]))
   y_train.append(np.array(data[i%8][1]))
  
x_train =np.array(x_train)
y_train = np.array(y_train)
print(x_train)
print(y_train)


[[0 0 0]
 [0 0 1]
 [0 1 0]
 ...
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[1]
 [1]
 [0]
 ...
 [0]
 [0]
 [0]]


In [0]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(3, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(50, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

In [0]:
model.compile(optimizer='adam',  # Good default optimizer to start with
              loss='sparse_categorical_crossentropy',  # how will we calculate our "error." Neural network aims to minimize loss.
              metrics=['accuracy'])  # what to track

In [0]:
print(len(x_train), len(y_train))
print(x_train.shape, y_train.shape)

model.fit(x_train, y_train, epochs=3)


10000 10000
(10000, 3) (10000, 1)
Epoch 1/3
10000/10000 [==============================] - 2s 178us/step - loss: 0.4665 - acc: 0.8718
Epoch 2/3
10000/10000 [==============================] - 0s 34us/step - loss: 0.2221 - acc: 0.9948
Epoch 3/3
10000/10000 [==============================] - 0s 34us/step - loss: 0.1266 - acc: 1.0000


In [0]:
prediction = model.predict(x_train)

In [0]:
for a in range(9,17):
  print(np.argmax(prediction[a]), x_train[a], y_train[a])

1 [0 0 1] [1]
0 [0 1 0] [0]
1 [0 1 1] [1]
0 [1 0 0] [0]
0 [1 0 1] [0]
0 [1 1 0] [0]
0 [1 1 1] [0]
1 [0 0 0] [1]


In [0]:

n_nodes_hl1 = 50
n_nodes_hl2 = 50

n_classes = 2
batch_size = 100

x = tf.placeholder('float', [None, 3])
y = tf.placeholder('float')

def neural_network_model(data):
    hidden_1_layer = {'weights':tf.Variable(tf.random_normal([3, n_nodes_hl1])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl1]))}
    

   

    output_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl2, n_classes])),
                    'biases':tf.Variable(tf.random_normal([n_classes])),}


    l1 = tf.add(tf.matmul(data,hidden_1_layer['weights']), hidden_1_layer['biases'])
    l1 = tf.nn.relu(l1)

 
    output = tf.matmul(l1,output_layer['weights']) + output_layer['biases']

    return output

def train_neural_network(x):
    prediction = neural_network_model(x)
    # OLD VERSION:
    #cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
    # NEW:
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y) )
    optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    hm_epochs = 10
    with tf.Session() as sess:
        # OLD:
        #sess.run(tf.initialize_all_variables())
        # NEW:
        sess.run(tf.global_variables_initializer())

        for epoch in range(hm_epochs):
            epoch_loss = 0
           
           #epoch_x, epoch_y = mnist.train.next_batch(batch_size)
            _, c = sess.run([optimizer, cost], feed_dict={x: x_train, y: y_train})
            epoch_loss += c

            print('Epoch', epoch, 'completed out of',hm_epochs,'loss:',epoch_loss)
       
     
        correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))
       

        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        print('Accuracy:',accuracy.eval({x:x_train, y:y_train}))

train_neural_network(x)


Epoch 0 completed out of 10 loss: 4.642450332641602
Epoch 1 completed out of 10 loss: 4.611840724945068
Epoch 2 completed out of 10 loss: 4.581241607666016
Epoch 3 completed out of 10 loss: 4.550579071044922
Epoch 4 completed out of 10 loss: 4.519972324371338
Epoch 5 completed out of 10 loss: 4.489450454711914
Epoch 6 completed out of 10 loss: 4.458799839019775
Epoch 7 completed out of 10 loss: 4.428130149841309
Epoch 8 completed out of 10 loss: 4.3975749015808105
Epoch 9 completed out of 10 loss: 4.3670878410339355
Accuracy: 1.0


In [0]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()


11493376/11490434 [==============================] - 0s 0us/step


In [0]:
print(y_train[7])
print(x_train.shape, y_train.shape)

3
(60000, 28, 28) (60000,)


In [0]:
print(x_train[7])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  38  43 105 255 253 253 253
  253 253 174   6   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  43 139 224 226 252 253 252 252 252
  252 252 252 158  14   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 178 252 252 252 252 253 252 252 252
  252 252 252 252  59   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 109 252 252 230 132 133 13